name: tlist
description: "A Todo list app with some aditional features"
homepage: https://list.novila.xyz
repository: https://github.com/friyn/tlist


publish_to: 'none'

version: 1.2.0+120

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  shared_preferences: ^2.5.3
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_database: ^12.0.0
  package_info_plus: ^8.0.2
  http: ^1.2.2
  url_launcher: ^6.3.0
  home_widget: ^0.8.0
  google_sign_in: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#128C7E"
  image: "assets/logo.png"
  android_gravity: center
  ios_content_mode: center
