// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE6Rw02MDEKHIe-aqYEoGuk9GYkj2eHG0',
    appId: '1:582262425557:web:bb5480d783f97b58029f5c',
    messagingSenderId: '582262425557',
    projectId: 'tlistserver',
    // authDomain: 'tlistserver.firebaseapp.com',
    authDomain: 'list.novila.xyz',
    storageBucket: 'tlistserver.firebasestorage.app',
    measurementId: 'G-GL9ZWVCBD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWYT98BF7VQr3y_qThu5wae0vG308nF6k',
    appId: '1:582262425557:android:81685a50fe61a2ad029f5c',
    messagingSenderId: '582262425557',
    projectId: 'tlistserver',
    storageBucket: 'tlistserver.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE6Rw02MDEKHIe-aqYEoGuk9GYkj2eHG0',
    appId: '1:582262425557:web:a2fb9a11a3eb69e6029f5c',
    messagingSenderId: '582262425557',
    projectId: 'tlistserver',
    // authDomain: 'tlistserver.firebaseapp.com',
    authDomain: 'list.novila.xyz',
    storageBucket: 'tlistserver.firebasestorage.app',
    measurementId: 'G-K1HVP6VG7G',
  );
}
